export const FRUIT_NAMES = {
  tomato: 'Tomate',
  strawberry: 'Erdbeere',
  apple: 'Apfel',
  orange: 'Orange',
  lemon: 'Zitrone',
  watermelon: 'Wassermelone',
  grape: 'Traube',
  cherry: 'Kirsche',
  peach: 'Pfirsich',
  blueberry: 'Blaubeere',
  carrot: 'Karotte',
  eggplant: 'Aubergine',
  corn: 'Mais',
  broccoli: 'Brokkoli',
  pumpkin: 'Kürbis',
  pea: 'Erbse',
  radish: 'Radieschen',
  onion: 'Zwiebel',
  potato: 'Kartoffel',
  banana: 'Banane',
  lime: 'Limette',
  pineapple: 'Ananas',
  melon: 'Honigmelone',
  kiwi: 'Kiwi',
  mango: 'Mango',
  pear: 'Birne',
  plum: 'Pflaume',
  pomegranate: 'Granatapfel',
  cabbage: 'Kohl',
  cucumber: 'Gurke',
  bellpepper: 'Paprika',
  kale: 'Grünkohl',
  garlic: 'Knoblauch',
  sweetpotato: 'Süßkartoffel',
  chili: 'Chili',
  cauliflower: 'Blumenkohl',
  leek: 'Lauch',
  turnip: 'Rübe',
} as const

export type FruitType = keyof typeof FRUIT_NAMES

export const FRUIT_CATEGORY: Record<FruitType, 'obst' | 'gemuese'> = {
  tomato: 'gemuese',
  strawberry: 'obst',
  apple: 'obst',
  orange: 'obst',
  lemon: 'obst',
  watermelon: 'obst',
  grape: 'obst',
  cherry: 'obst',
  peach: 'obst',
  blueberry: 'obst',
  carrot: 'gemuese',
  eggplant: 'gemuese',
  corn: 'gemuese',
  broccoli: 'gemuese',
  pumpkin: 'gemuese',
  pea: 'gemuese',
  radish: 'gemuese',
  onion: 'gemuese',
  potato: 'gemuese',
  banana: 'obst',
  lime: 'obst',
  pineapple: 'obst',
  melon: 'obst',
  kiwi: 'obst',
  mango: 'obst',
  pear: 'obst',
  plum: 'obst',
  pomegranate: 'obst',
  cabbage: 'gemuese',
  cucumber: 'gemuese',
  bellpepper: 'gemuese',
  kale: 'gemuese',
  garlic: 'gemuese',
  sweetpotato: 'gemuese',
  chili: 'gemuese',
  cauliflower: 'gemuese',
  leek: 'gemuese',
  turnip: 'gemuese',
}

export const FRUIT_KEYS = Object.keys(FRUIT_NAMES) as FruitType[]

export function randomFruitType(): FruitType {
  return FRUIT_KEYS[Math.floor(Math.random() * FRUIT_KEYS.length)]
}
